### ISSUE TITLE
How config generic interface

### ISSUE THREAD

**Issue by tillig** [autofac/Autofac.Configuration#1]
_From @hbulzy on November 18, 2015 13:56_

config like this 
 <component instance-scope="per-dependency"
                   type="SYS.Data.Repository2`1, SYS.Framework"
                   service="SYS.Data.IRepository`1">
      </component>
i got a error 
System.ArgumentException: The type 'SYS.Data.Repository2`1[T]' is not assignable to service 'SYS.Data.IRepository`1'.

_Copied from original issue: autofac/Autofac#696_

**Comment by tillig** [comment]
You can't register open generics via configuration, and `IRepository`1` is an open generic - it's the same as saying `.As<IRepository<>>()` on a registration without specifying the generic type parameter.

**The best way to figure out what the string type names are is to try writing them out in a simple console app, then use `Type.GetType` to see if you can use the same string to get the type back.**

For example, if I wanted to register something `.As<IEnumerable<string>>()` via config, I need to figure out what the type name of `IEnumerable<string>` is and that's what would go in the `service` entry. The same goes for the `type` of the component - try writing the type name out to the console and seeing if you can do `Type.GetType` to get it back:

``` csharp
var name = typeof(IEnumerable<string>).FullName;
Console.WriteLine(name);
// name is
// System.Collections.Generic.IEnumerable`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]

var type = Type.GetType(name);
Console.WriteLine(type.FullName);
// This should also write out
// System.Collections.Generic.IEnumerable`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
```

**Comment by hbulzy** [comment]
Oh thank you! i ‘ll change my code,find another way!
