### ISSUE TITLE
Passing ResolvedParameter to Resolve in Autofac.Configuration are not supported.

### ISSUE THREAD

**Issue by Clark159** [autofac/Autofac.Configuration#11]
I read this document : [JSON/XML Configuration](http://docs.autofac.org/en/latest/configuration/index.html). Passing ResolvedParameter to Resolve in Autofac.Configuration are not supported.

- autofac.json

        {
            "components": [

                // MainClass
                {
                    "type": "ConsoleApplication1.MainClass, ConsoleApplication1",
                    "services": [
                    {
                        "type": "ConsoleApplication1.MainClass, ConsoleApplication1",
                        "key": "default"
                    }
                    ],
                    "parameters": {
                    // "sub": {} // How to set ResolvedParameter?
                    }
                },

                // SubClass
                {
                    "type": "ConsoleApplication1.SubClassA, ConsoleApplication1",
                    "services": [
                    {
                        "type": "ConsoleApplication1.SubClass, ConsoleApplication1",
                        "key": "default"
                    }
                    ]
                }
            ]
        }

- Program.cs

        using Autofac;
        using Autofac.Configuration;
        using Autofac.Core;
        using Microsoft.Extensions.Configuration;
        using System;
        using System.Collections.Generic;
        using System.Linq;
        using System.Text;
        using System.Threading.Tasks;

        namespace ConsoleApplication1
        {
            class Program
            {
                // ByCode
                static void Main(string[] args)
                {
                    // AutofacBuilder    
                    var autofacBuilder = new ContainerBuilder();
                    autofacBuilder.RegisterType<SubClassA>().Keyed<SubClass>("default");
                    autofacBuilder.RegisterType<MainClass>().Keyed<MainClass>("default").WithParameter(ResolvedParameter.ForKeyed<SubClass>("default"));

                    // AutofacContainer
                    var autofacContainer = autofacBuilder.Build();
            
                    // Resolve
                    var mainClass = autofacContainer.ResolveKeyed<MainClass>("default");

                    // End
                    Console.WriteLine("End...");
                    Console.ReadLine();
                }

                // ByConfig
                static void Main2(string[] args)
                {
                    // AutofacConfig
                    var autofacConfig = new ConfigurationBuilder().AddJsonFile("autofac.json").Build();
                    if (autofacConfig == null) throw new InvalidOperationException();
            
                    // AutofacBuilder    
                    var autofacBuilder = new ContainerBuilder();
                    autofacBuilder.RegisterModule(new ConfigurationModule(autofacConfig));

                    // AutofacContainer
                    var autofacContainer = autofacBuilder.Build();

                    // Resolve
                    var mainClass = autofacContainer.ResolveKeyed<MainClass>("default"); //<--Error

                    // End
                    Console.WriteLine("End...");
                    Console.ReadLine();
                }
            }

            public class MainClass
            {
                public MainClass(SubClass sub)
                {
                    sub.Show();
                }
            }

            public interface SubClass
            {
                void Show();
            }

            public class SubClassA : SubClass
            {
                public void Show()
                {
                    Console.WriteLine("SubClassA.Show");
                }
            }
        }

**Comment by tillig** [comment]
You're correct, passing a resolved parameter instead of a fixed value parameter isn't supported. There's not a lot of value in trying to replicate code inside config. If you need that, look at using Autofac modules instead and configure the module rather than the registration.
