### ISSUE TITLE
Passing constructor parameters from a config file does not work

### ISSUE THREAD

**Issue by tillig** [autofac/Autofac.Configuration#12]
_From @arnamq on March 21, 2017 8:11_

Hi,

When I try to pass a constructor parameter from the config file it is ignored by the method IContainer.ResolveNamed.

My config looks like that:
```
     "parameters":{
        "constructorParamName":["stringValue1", "stringValue2"]
     }
```
and the constructor:

`public MyClassConstructor(IList<string> constructorParamName = null) `

Passing properties works fine.

Best regards,
arnam

_Copied from original issue: autofac/Autofac#837_

**Comment by tillig** [comment]
@arnamq Does it work if the constructor parameter is not optional?

**Comment by arnamq** [comment]
No it doesn't work either.

**Comment by tillig** [comment]
I added some unit tests [in this commit](https://github.com/autofac/Autofac.Configuration/commit/67453c425d427418eb158dc2034a539836287ec0) to verify that enumerable/list parameters in a constructor work... and they do.

What that means is I'm unable to reproduce the issue. Do you have a small repro project where I can see this in action?

**Comment by arnamq** [comment]
I've done some additional tests and figured out the right test case.

The problem appears only if I have constructor with parameter with default 'null' value like

`public TestClassConstructor(IList<string> constructorParameter = null)` 

Even if a class has only one constructor like this one above the constructor parameter isnt's passed. If I have two constructor ex.:

`public TestClassConstructor(IList<string> constructorParameter)`
`public TestClassConstructor()`  

...a constructor parameter isnt't passed too. Autofac uses default constructor with no parameters.

**Comment by tillig** [comment]
I added some unit tests [in this commit](https://github.com/autofac/Autofac.Configuration/commit/ad0cb4c98b7d35902e9fc61940eb12e4a0d21d82) to test the scenarios you mentioned:

- A class that has a default null parameter.
- A class that has multiple constructors.

In both cases the constructor parameter was correctly filled in.

Again, I can't repro the issue. If you can provide me with a failing unit test, I can continue looking into it; otherwise there's nothing I can do.

**Comment by arnamq** [comment]
...OK - the problem was that I tried to create an instance of a derived class which didn't have overrided constructors so autofac Was calling default constructor from a base class.

Summarizing: there is no bug in an Autofac or Autofac.Configuration libraries.

Thank you for your help and tests and sorry for bothering you!

Best regards,
arnam
