### ISSUE TITLE
How do I register a named service in JSON?

### ISSUE THREAD

**Issue by timosnel** [autofac/Autofac.Configuration#13]
I'm working on migrating a project that uses version 3.3.0 of Autofac.Configuration to version 4.0.1. Choosing for the JSON way, how can I register a named service? Previously it was done like this:

```xml
<component
  type="MyAssembly.StorageProvider, MyAssembly"
  service="MyAssembly.IStorageProvider, MyAssembly"
  name="provider">
</component>
```
I tried the following, which doesn't work:
```json
{
  "type": "MyAssembly.StorageProvider, MyAssembly",
  "services": [ { "type": "MyAssembly.IStorageProvider, MyAssembly" } ],
  "name": "provider"
}
```
I can't find anything about named/keyed services in the docs, only metadata. Is this currently supported? If not, does the required name attribute for the XML option represent a named service?

**Comment by tillig** [comment]
Use `key` instead of `name`. `name` is a reserved word in the Microsoft XML configuration source so we can't use that. [You'll find `key` shown in the documentation.](http://autofac.readthedocs.io/en/latest/configuration/xml.html#configuring-with-microsoft-configuration-4-0)

```json
{
  "components": [{
    "type": "Autofac.Example.Calculator.Addition.Add, Autofac.Example.Calculator.Addition",
    "services": [{
      "type": "Autofac.Example.Calculator.Api.IAddOperation",
      "key": "add"
    }]
  }]
}
```
