### ISSUE TITLE
MSBuild not copying JSON config file to output directory

### ISSUE THREAD

**Issue by nobels** [autofac/Autofac.Configuration#16]
In the past with version 3 i had a working mechanism with references in the config file.

From know on it's changed to JSON files. (or XML)

I build 2 projects and i don't get version 4 to work with autofac configuration.

I am nearly there but it's the loading where it' fails.

FYI: 

Version 3 = Working like it should.
Version 4 = Json problem

Autofac.PrinterV3 (Version 3) loads the dll by app.config
```
 <autofac>
     <modules>
       <module type="Autofac.BaseV3.Autofac.BaseV3Module, Autofac.BaseV3" />
     </modules>
</autofac>
```

With Autofac.Printer (Version 4) loads the dll by autofac.json

```
{
  "modules": [
    {"type": "Autofac.Base.Autofac.BaseModule, Autofac.Base"}
  ]
}

```

Problem:

Autofac.Json file is not perform copy even with property "Copy always on"

i have a readme.txt to compare with -> there i don't have any problems.

Retrieving the modules from the json file not possible even if i manualy place the config in debug folder.

**Example projects to reproduce the problem:**
Here is te location for rar file with package https://www.dropbox.com/s/hh5qob660t5ltr1/AutofacExample-Complete.rar?dl=0

Here is the rar file without package file   https://www.dropbox.com/s/x8b8b7zr2gps8jl/AutofacExample.rar?dl=0

Can somebody help me out on this ?

Thanks

**Comment by tillig** [comment]
Question originally posted to [Autofac Google Group here](https://groups.google.com/forum/m/#!topic/autofac/QO5UXk-cgVU)

**Comment by tillig** [comment]
Before we dive in here it's important to note that the thing that does file copying to build output is Visual Studio and/or MSBuild; and the thing that reads the configuration in and parses the JSON or XML is Microsoft.Extensions.Configuration. Neither of these is Autofac.

**Comment by nobels** [comment]
Ok, but the copy problem is not my concern. (just a remark)
If i manualy place the file there autofac behavoir is not normal.

This is the main focus. (i need to mention this)

**Comment by tillig** [comment]
The copy problem can be solved by selecting `autofac.json` in your project and, in the properties window in VS, change it to "Copy to Output Directory = Copy Always."

The reason your configuration isn't being registered is because you're not putting your `ConfigurationModule` into your singleton `ContainerBuilder`.

```csharp
            var module = new ConfigurationModule(config.Build());
            var builder = new ContainerBuilder();
            builder.RegisterModule(module);

            this.Container = this.ContainerBuilder.Build();
```

You're just putting the module into some random other `ContainerBuilder` instance.

Change it to:

```csharp
            var module = new ConfigurationModule(config.Build());
            this.ContainerBuilder.RegisterModule(module);

            this.Container = this.ContainerBuilder.Build();
```
