### ISSUE TITLE
IOptions<T> in JSON configuration

### ISSUE THREAD

**Issue by lurumad** [autofac/Autofac.Configuration#17]
Hi, 

I'm playing with JSON configuration in .NET Core app. I wonder if is possible to configure for example RedisCache using JSON configuration approach:

```c#
    public RedisCache(IOptions<RedisCacheOptions> optionsAccessor)
    {
      if (optionsAccessor == null)
        throw new ArgumentNullException("optionsAccessor");
      this._options = optionsAccessor.Value;
      this._instance = this._options.InstanceName ?? string.Empty;
    }
```
I don't know if is possible configure options in JSON file.

Regards!

**Comment by tillig** [comment]
Options is sort of a magical beast where you actually register `IConfigureOptions<T>` instances and a factory they provide runs them all. I would guess if you registered those via config it should work but the actual syntax is going to be "an exercise for the reader" (a good StackOverflow question if you try and can't figure it out).

[Dive into the Options repo to see how it works](https://github.com/aspnet/Options/tree/dev/src/Microsoft.Extensions.Options) - knowing how they build up the options will help you understand what I'm saying.

And keep in mind config isn't intended to be a feature for feature replacement for registrations. You can work around complex things by using config with Autofac modules.

**Comment by lurumad** [comment]
Totally agree with you!

Thanks!
