### ISSUE TITLE
EnableClassInterceptor

### ISSUE THREAD

**Issue by stefannikolei** [autofac/Autofac.Configuration#19]
Hello,

i am trying to use the json based configuration. At the moment i am stuck with Interceptors. Is there a way, to enable the ClassInterception. 

This is my registration
```
 builder.RegisterType<ItemRepository>().As<IItemRepository>().EnableClassInterceptors();
```
How would this be written in json?

**Comment by tillig** [comment]
As noted [in the docs](http://autofac.readthedocs.io/en/latest/configuration/xml.html)...

> Configuration in JSON/XML is not a feature-for-feature replacement for programmatic configuration, so complex scenarios may require a combination of JSON/XML and modules.

JSON config doesn't support configuring interceptors. Consider combining config with [modules](http://autofac.readthedocs.io/en/latest/configuration/modules.html) to get the job done.
