### ISSUE TITLE
Conversion of string to parameter/property value doesn't specify culture

### ISSUE THREAD

**Issue by tillig** [autofac/Autofac.Configuration#26]
[From this StackOverflow question](https://stackoverflow.com/questions/55533108/how-to-define-default-autofac-locale-used-when-parsing-json-xml-configuration): The `TypeManipulation` code doesn't specify a culture when converting string values to other types so behavior may change based on the local machine's current culture.

The quickest fix would be to use `CultureInfo.InvariantCulture` everywhere - this is how ASP.NET handles parsing querystrings to ensure it's agnostic to local machine culture.

**Comment by jirigargas** [comment]
Hi, is there any estimate when this could be fixed? I can't be the only one who encountered this issue as there are 150 different cultures. And not all of them uses dots as decimal separator ...

**Comment by tillig** [comment]
No estimate. There are only two project maintainers for core Autofac and 20+ integration libraries and we are entirely unpaid doing this in our spare time. If you'd like it fixed faster, send a PR. The fix should be to specify invariant culture where a culture is required.

**Comment by bcisnero** [comment]
I'll take care of it

**Comment by tillig** [comment]
I believe I have a fix for this that will be coming out in Autofac.Configuration 5.0 along with Autofac 5.0 compatibility. If it still doesn't fix the issue, open a new issue and please provide a failing test that we can use to verify the fix later.
