### ISSUE TITLE
InstancePerMatchingLifetimeScope

### ISSUE THREAD

**Issue by vishiitr** [autofac/Autofac.Configuration#28]
How can I register the scope as InstancePerMatchingLifetimeScope as provided by the Autofac. As of now it is throwing my exception as Invalid Scope.

**Comment by tillig** [comment]
As noted in the issue template...

> If you have a usage question ("How do I...?" "Others have this working but I can't get it...") please try [StackOverflow](https://stackoverflow.com/) and tag your question `autofac`. We, along with a great community, monitor those questions.

[We also have plenty of docs.](https://autofac.readthedocs.io/en/latest/)
