### ISSUE TITLE
IConfigurationRoot is not assignable to IConfiguration parameter type, sample/test broken

### ISSUE THREAD

**Issue by beachwalker** [autofac/Autofac.Configuration#3]
The description about using ConfigurationModule does not work (does not even compile).

How to use ConfigurationModule as described here: http://autofac.readthedocs.org/en/latest/configuration/xml.html#quick-start does not work.

// Add the configuration to the ConfigurationBuilder.
var config = new ConfigurationBuilder();
config.AddJsonFile("autofac.json");

// Register the ConfigurationModule with Autofac.
**_var module = new ConfigurationModule(config.Build());**_
var builder = new ContainerBuilder();
builder.RegisterModule(module);

The config.Build() returns **_IConfigurationRoot**_ but ContainerBuilder requires **_IConfiguration**_ parameter.

 Seems MS changed the API a little bit. Is there a way to create configuration from IConfiguraionRoot?

**Comment by beachwalker** [comment]
It worked with beta, broken since release candidate.
There is no Unit Test for ConfigurationModule.

**Comment by beachwalker** [comment]
Seems there is a problem with Microsoft.Extensions.Configuration (used by Autofac.Configuration) and the Documentation which states to use Microsoft.Framework.Configuration.

**Comment by beachwalker** [comment]
The problem is announced here:
https://github.com/aspnet/Announcements/issues/77
https://github.com/aspnet/Configuration/issues/304

Just add Assemblies with Microsoft.Extensions.Configuration.\* name instead of the former Microsoft.Framework.Configuration.\* names to solve the Problem.

Anyway, I leave this open until the documentation is fixed.

**Comment by tillig** [comment]
PR accepted, docs updated. Thanks!
