### ISSUE TITLE
Dynamic loading not working with json file configuration with net core 3.1

### ISSUE THREAD

**Issue by beachwalker** [autofac/Autofac.Configuration#31]
When trying to load an assembly using the configuration module using a configuration file without having a direct dependency to the referenced assembly that needs to be loaded (My.Module1.dll in example below) the loading of these assembly type fails (Type.GetType() call returns null). This might be a result of the changed behaviour  between net core and net framework, so the configuration module might still work in net framework.

The problem occurs in src/Autofac.Configuration/Core/ConfigurationExtensions.cs
        public static Type GetType(this IConfiguration configuration, string key, Assembly defaultAssembly)

https://github.com/autofac/Autofac.Configuration/blob/84768696f1cf0e1e77fbb32621e4469aeddc88df/src/Autofac.Configuration/Core/ConfigurationExtensions.cs#L202

The occuring exception:
> `System.InvalidOperationException: "The type 'My.Module1.SomeModule, My.Module1' could not be found. It may require assembly qualification, e.g. "MyType, MyAssembly".`"

My configuration section:

```
  "Modules": [
    {
      "type": "My.Module1.SomeModule, My.Module1"
    }
  ]
```

If I make the My.Module1 assembly a project dependency in Visual Studio everything works (because the assembly is automatically loaded as dependency outside of the scope of Autofac.Configuration).
However, if I don't make this an explicit dependency the dynamic loading does not work with net core. This reduces the usability of the Configuration package because you need to know all dependencies in front at compile time (not only runtime).

Issue occurs with Autofac configuration 5.1.0 in netcore 3.1.

Referenced packages:

>     <PackageReference Include="Autofac" Version="5.1.2" />
>     <PackageReference Include="Autofac.Configuration" Version="5.1.0" />
>     <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="6.0.0" />
>     <PackageReference Include="Autofac.Extras.AttributeMetadata" Version="5.0.0" />
>     <PackageReference Include="Caliburn.Micro" Version="4.0.117-alpha" />
>     <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.2" />
>     <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="3.1.2" />
>     <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="3.1.2" />
>     <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.1.2" />
>     <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="3.1.2" />
>     <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="3.1.3" />
>     <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="3.1.2" />
>     <PackageReference Include="Microsoft.Extensions.Options" Version="3.1.2" />
>     <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="3.1.2" />
>     <PackageReference Include="Serilog.Extensions.Logging" Version="3.0.1" />

**Comment by tillig** [comment]
Autofac is not responsible for assembly loading. It can use things loaded into your application, but the .NET Core framework does the loading, not Autofac. [We have an example showing one way to handle plugins in .NET Core](https://github.com/autofac/Examples/blob/master/src/ConfigurationExample/Program.cs) however we have no specific guidance or additional troubleshooting - assembly loading is a framework concern; if you have questions about guidance on dynamically loading assemblies, the .NET Core team is a better candidate to ask questions.

**Comment by beachwalker** [comment]
Ok, but this means a different behavior of the Autofac.Configuration between netcore and net framework. Clients will run into this.

**Comment by tillig** [comment]
Autofac has never been responsible for assembly loading, in any of the frameworks. That each framework loads assemblies differently (e.g., an application in .NET desktop framework might automatically load everything in the bin folder) isn't something remotely in the control of Autofac.

I did [add an issue](https://github.com/autofac/Documentation/issues/101) to explain this in an FAQ, but the FAQ will basically be what I just mentioned - assembly loading and plugin concerns have never been part of Autofac and we can't really provide guidance on it due to the number of considerations one might need to make in adequately addressing plugins. I'm sorry we can't offer you more than that.

**Comment by beachwalker** [comment]
No problem. Due to the benefits of open source development I can "fix" this issue on my own and solve this. Maybe I change this to an independent library then to provide this feature to the community. Anyway thanks for your work. :-)
