### ISSUE TITLE
Modules collection should be ordinal

### ISSUE THREAD

**Issue by Shalma** [autofac/Autofac.Configuration#34]
Since 3 days, i have this error on photon with autofac json config file.
![image](https://user-images.githubusercontent.com/14791219/93269875-30028e00-f7b0-11ea-9118-3f9f3ba460eb.png)

I made many research, and I can't find anything :s 
Autofac version : 5.2.0
Autofac.configuration version : 5.1.0
Microsoft.Extensions.Configuration version: 3.1.8

I set up my config file as json, like this : 
![image](https://user-images.githubusercontent.com/14791219/93269922-4c062f80-f7b0-11ea-9762-6e711381000a.png)

and in my PhotonApplication, i set up like this :
![image](https://user-images.githubusercontent.com/14791219/93269993-6b04c180-f7b0-11ea-80e5-a8f033cd76bf.png)

I also tried as XML file, with name attribute, but i also have this error.
Is someone can help me please ? :)

**Comment by tillig** [comment]
Can you actually paste the JSON here (use triple-backticks around it so we can see it as JSON) so we can see it without retyping it?

````
```json
{
  "put": "your json",
  "inside": "backtick fences"
}
```
````

Same thing with the code.

````
```c#
public void PutYourCode(string insideFences)
{
}
```
````

The reason this is important is that if your code has a typo in it, we may not be able to re-create that if we manually type it ourselves.

**Comment by Shalma** [comment]
No prob, there is it :) 
```json
{
  "defaultAssembly": "MultiplayerGameFramework",
  "components": [{
    "type": "MultiplayerGameFramework.Implementation.Config.ServerConfiguration, MultiplayerGameFramework",
    "parameters": {
      "allowPhysicalClients": true,
      "parentPort": 4530,
      "siblingPort": 0,
      "subCodeParameterCode": 0,
      "peerIdCode": 1
    }
   }],
  "modules": [{
    "type": "MGF_Photon.Modules.ProxyServerModule, MGF_Photon"
  }]
}
```

```c#
var config = new ConfigurationBuilder();
//config.AddXmlFile(Path.Combine(BinaryPath, ApplicationName + ".config"));
config.AddJsonFile(Path.Combine(BinaryPath, ApplicationName + ".json"));

var module = new ConfigurationModule(config.Build());

// Create the autofac container
var builder = new ContainerBuilder();
builder.RegisterInstance(this).SingleInstance();
builder.RegisterInstance(Log).As<ILogger>().SingleInstance();
builder.RegisterModule(module);

var container = builder.Build();
```

And in case, there is my xml file, which generate the same error if i use it :
```xml
<?xml version="1.0" encoding="utf-8" ?>
<autofac defaultAssembly="MultiplayerGameFramework">
  <components name="0">
    <type>MultiplayerGameFramework.Implementation.Config.ServerConfiguration, MultiplayerGameFramework</type>
    <parameters>
      <allowPhysicalClients>true</allowPhysicalClients>
      <parentPort>4530</parentPort>
      <siblingPort>0</siblingPort>
      <subCodeParameterCode>0</subCodeParameterCode>
      <peerIdCode>1</peerIdCode>
    </parameters>
  </components>
  <modules name="1">
    <type>MGF_Photon.Modules.ProxyServerModule, MGF_Photon</type>
  </modules>
</autofac>
```

**Comment by alistairjevans** [comment]
I've run a test on my side using the exact JSON you are using, and the same component+module combination, and I do not see the error you see.

The module and component load OK; no error.  

Just to rule out the easy stuff, let's dump the raw config to Trace so we can check we're getting the config structure we expect:

In your C# code, build the config, then write each value in the config out somewhere (I've used `Trace.WriteLine` here, but whatever works):

```csharp
var config = new ConfigurationBuilder();
config.AddJsonFile(Path.Combine(BinaryPath, ApplicationName + ".json"));

var builtConfig = config.Build();

foreach (var kvp in builtConfig.AsEnumerable())
{
    Trace.WriteLine($"{kvp.Key} => {kvp.Value}");
}
```

When I run that with the JSON file you gave, I get the following (type names are different from yours):

```
modules => 
modules:0 => 
modules:0:type => Autofac.Configuration.Test.Core.ModuleConfiguration_Issue34+ProxyServerModule, Autofac.Configuration.Test
defaultAssembly => Autofac.Configuration.Test
components => 
components:0 => 
components:0:type => Autofac.Configuration.Test.Core.ModuleConfiguration_Issue34+Component1, Autofac.Configuration.Test
components:0:parameters => 
components:0:parameters:subCodeParameterCode => 0
components:0:parameters:siblingPort => 0
components:0:parameters:peerIdCode => 1
components:0:parameters:parentPort => 4530
components:0:parameters:allowPhysicalClients => True
```

Do you get the same?

**Comment by Shalma** [comment]
I'v got this :
```
modules => 
modules:0 => 
modules:0:type => MGF_Photon.Modules.ProxyServerModule, MGF_Photon
defaultAssembly => MultiplayerGameFramework
components => 
components:0 => 
components:0:type => MultiplayerGameFramework.Implementation.Config.ServerConfiguration, MultiplayerGameFramework
components:0:parameters => 
components:0:parameters:subCodeParameterCode => 0
components:0:parameters:siblingPort => 0
components:0:parameters:peerIdCode => 1
components:0:parameters:parentPort => 4530
components:0:parameters:allowPhysicalClients => True
```

And finally, the server is running and work :)
I just cleanup the deploy/bin directory, i don't know why, but it seems there were some cache. 
Thanks for the time you pass :)
