### ISSUE TITLE
Encapsulated Configuration causing module to be registered twice.

### ISSUE THREAD

**Issue by a1dancole** [autofac/Autofac.Configuration#35]
## Describe the Bug

Autofac configuration is causing module that use Encapsulated Configuration to be registered twice, the second time without properties injected

## Steps to Reproduce

I've created a repo with a very basic app replicating this issue. https://github.com/a1dancole/Autofac.Configuration.Issue

1. Create a new module with properties
2. Create and register a new ConfigurationModule
3. Add properties into appsettings.json in Microsoft.Extensions.Configuration format
4. Register module with ContainerBuilder
5. Debug and breakpoint in the module. The breakpoint will be hit twice, the first time with properties populated, the second time with properties being null

## Expected Behavior

The module should be registered once using properties injected from ConfigurationModule

## Exception with Stack Trace

```text
Put the exception with stack trace here.
```

## Dependency Versions

Autofac: v6.0.0
Autofac.Configuration: v6.0.0
Autofac.Extensions.DependencyInjection: v7.1.0

## Additional Info

I hope the repository reproducing this issue is enough, but I can provide screen shots and traces of the errors if required

**Comment by tillig** [comment]
Your configuration [registers your `TestModule`](https://github.com/a1dancole/Autofac.Configuration.Issue/blob/daaf9744d3d9365feb6ff2b9841e91b01082aafc/Autofac.Configuration.Issue/appsettings.json#L12) _and_ your `Startup` [also registers `TestModule`.](https://github.com/a1dancole/Autofac.Configuration.Issue/blob/daaf9744d3d9365feb6ff2b9841e91b01082aafc/Autofac.Configuration.Issue/Startup.cs#L42)

If you only want it registered once you'll need to remove one of those. Modules are not unique entities and it's perfectly valid to register a module twice (eg, with different parameters each time).

**Comment by a1dancole** [comment]
Right. Thank you, that does make sense. I must have missed something in the documentation that adding the module into configuration also adds that module to the builder.
