### ISSUE TITLE
New Configuration ignores inherited properties

### ISSUE THREAD

**Issue by beachwalker** [autofac/Autofac.Configuration#4]
It seems the bug #2 is not only limited to using Json files.

When I use a Module as in the snippet below

``` csharp
public class ShellModule : Module
{
    protected override void Load(ContainerBuilder builder)
    {
        builder.RegisterType<MyShell>()
                     .WithProperty("DisplayName", "HelloW")
                     .As<IShell>();
    }
}
```

... the property is only set if the property belongs to MyShell or is at least overriden. The sample code is the same as in issue #2:

``` csharp
public interface IShell
{
}

public class MyShellBase : IShell
{
     public virtual string DisplayName { get; set; }
}

   // unable to set DisplayName from MyShellBase through module / .WithProperty() 
public class MyShell : MyShellBase
{
}

// now it works with module
public class MyShell : MyShellBase
{
     public override string DisplayName { get; set; }  // why do I have to define again?
}
```

Maybe it is a problem with Autofac itself and not only the Config!?

This is how I bootstrap the builder:

``` csharp
var config = new ConfigurationBuilder();
foreach (var file in directory.GetFiles("*.json"))
{
    config.AddJsonFile(file.FullName);
}
foreach (var file in directory.GetFiles("*.xml"))
{
    config.AddXmlFile(file.FullName);
}
builder.RegisterModule(new ConfigurationModule(config.Build()));

```

**Comment by tillig** [comment]
Closing as duplicate for #2.

**Comment by beachwalker** [comment]
Hmm, seems like a big problem for me if .WithProperty("DisplayName", "HelloW") does not work anymore. Not worth to stay as a separate bug? ;-)

The inner problem is that I can't set a property using:

``` csharp
        builder.RegisterType<MyShell>()
                     .WithProperty("DisplayName", "HelloW")
                     .As<IShell>();
```

From my point of view this is currently a **_blocker**_ with the new release candidate.

I was not able to find a test where derrived classes and virtual properties are tested and set. Do I miss something?

**Comment by tillig** [comment]
Agreed, and we'll take care of it (unless you want to push a PR, which we'd accept). There's a lot we're working on and this is one of the many things. [You can see the other challenges we're running into with ASP.NET 5 and the conversion effort over here.](https://github.com/autofac/Autofac/issues/594)
