### ISSUE TITLE
JSON Configuration and Modules

### ISSUE THREAD

**Issue by SoftwareDesign-Solution** [autofac/Autofac.Configuration#40]
How can I register modules in JSON Configuration? I have two SQL Connections in the main program and I would like to use the connections in the class library that the module exists.

**Comment by tillig** [comment]
As noted in the issue template, "How Do I...?" questions need to go to StackOverflow. You might want to slow down and [read the documentation](https://autofac.readthedocs.io/en/latest/configuration/xml.html), too, because the answers are there.
