### ISSUE TITLE
Autofac.Configuration - 4.0.0-rc2-279 does not  support .net 4.5.1

### ISSUE THREAD

**Issue by igatanasov** [autofac/Autofac.Configuration#6]
Hi,

I have just saw that the latest package - 4.0.0-rc2-279 does not support .net 4.5.1.

Can you bring it back, since in Autofac.Configuration.4.0.0-rc2-271 is available?

**Comment by tillig** [comment]
Sorry about that, the netstandard target framework moniker shifts are confusing. Let me see what I can do.

**Comment by tillig** [comment]
Thanks for catching this. Updated and pushed as [4.0.0-rc2-281](https://www.nuget.org/packages/Autofac.Configuration/4.0.0-rc2-281). Let me know if it doesn't work.

**Comment by igatanasov** [comment]
Hi @tillig ,

It works as expected, thanks.
