### ISSUE TITLE
"Autofac.Configuration 4.0.0-rc2-281" has a dependency on the unpublished "Autofac >= 4.0.0-rc2-263"

### ISSUE THREAD

**Issue by ghost** [autofac/Autofac.Configuration#7]
**Autofac.Configuration 4.0.0-rc2-281** has a dependency on **Autofac (>= 4.0.0-rc2-263).**
But the latest version of Autofac on NuGet is **Autofac 4.0.0-rc2-240**.

https://www.nuget.org/packages/Autofac.Configuration
https://www.nuget.org/packages/Autofac.Configuration/4.0.0-rc2-281
https://www.nuget.org/packages/Autofac/

**Comment by tillig** [comment]
I think NuGet local package cache strikes again.

I'll publish an updated RC2 package to help folks still on RC2 then try and get a .NET Core RTM compatible package out.

**Comment by ghost** [comment]
Thanks, that'd be great.

It's .NET Core we're targeting, and hopefully Autofac will fulfil our IoC Container needs on that platform.

**Comment by tillig** [comment]
Just pushed 4.0.0-rc2-286 that should fix your reference issue. I'm going to push an RTM compatible version "RC3" shortly.
