### ISSUE TITLE
Nested list in dictionary property through Autofac.Configuration in JSON are not supported

### ISSUE THREAD

**Issue by beachwalker** [autofac/Autofac.Configuration#8]
I use the new model of the Autofac.Configuration but I can't use nested property configuration. The following property **_NestedListInDictPropThatDoesNotWork_** is not working:

```
    "type": "Some.Modules.CoolModule, Some.Modules",
    "properties": {
        "StringProp": "hello world",
        "IntProp": 8090,
        "BoolProp": false,
        "DictProp": { "key": "value" },
        "ListProp": [1, 2, 3, 4, 5],
        "NestedListInDictPropThatDoesNotWork": {
            "myKey": [ "A", "B" ]
        }
```

Do I have to use an other syntax for that? I want to configure a Dictionary, where the value is a List of items instead of a simple value type.

I also posted this question to [stackoverflow](http://stackoverflow.com/questions/40109369/nested-list-in-dictionary-property-through-autofac-configuration-in-json).

I use Autofac.Configuration.4.0.1.

**Comment by tillig** [comment]
The configuration library isn't doing full "model binding" to figure out property values. It's a much simpler mechanism using a flatter binding concept - much closer to what the classic XML style configuration supported (more "key/value pair" than "recursive binding").

You can [see how we parse dictionaries here](https://github.com/autofac/Autofac.Configuration/blob/develop/src/Autofac.Configuration/Util/ConfiguredDictionaryParameter.cs#L11). It's trying type converters and casting on the value.

To understand why that doesn't "just work," think about how Microsoft.Extensions.Configuration parses this configuration. It's all key/value pairs to that system:

```
"type" = "Some.Modules.CoolModule, Some.Modules"
"properties:StringProp" = "hello world"
"properties:IntProp" = "8090"
"properties:BoolProp": "false"
"properties:DictProp:key": "value"
"properties:ListProp:0" = "1"
"properties:ListProp:1" = "2"
"properties:ListProp:2" = "3"
"properties:ListProp:3" = "4"
"properties:ListProp:4" = "5"
"properties:NestedListInDictPropThatDoesNotWork:myKey:0" ="A"
"properties:NestedListInDictPropThatDoesNotWork:myKey:1" ="B"
```

The Autofac configuration stuff does its best to try to "infer" what is meant by each property, but it's not an actual model binder. At the time we originally wrote this, the [Microsoft.Configuration.Extensions.Binder](https://github.com/aspnet/Configuration/tree/dev/src/Microsoft.Extensions.Configuration.Binder) stuff wasn't there and when it started getting there, it wasn't quite where we needed it. That may be a better option for us now that .NET Core has settled down a bit.

We'd be happy to take a pull request with an update for this support. In the meantime, I'll mark the issue as an enhancement request.

Also, if you wouldn't mind, in the future try not to cross-post to both the issues list and StackOverflow - try StackOverflow first. Cross-posting the question means we have to cross post the answer and make sure everyone knows where to go for further discussion. It gets confusing. Thanks!

**Comment by tillig** [comment]
Resolved by https://github.com/autofac/Autofac.Configuration/commit/f9e56449d2dafc9b5631c1bf5aac26c610ca5d58 - will release this shortly.
